sudo: true
language: node_js
node_js:
- '14'
script:
- cd generator
- bash ./deploy.sh
branches:
  only:
  - master
  - draft
env:
  global:
    secure: sJoKVDfE6/qP9hD9ZfZ+bq/q3or3AXlAn6YBxvB7GPeMPRkrdPoKR7BgEoPo1YqP4LNwKQ67dqftu6cFnmQfOxbPNfy+U0cwjzRH17I2v72wdsIMKNHmUkoo7aYBoJKrKfoH8k/xdF8+vvVVRaessC38ImQWQdfEfoMEQEpC7g/iLKyVl8+F2/SDPqshw2I1zgM5fbHYbn3Ob8uhE8VuU8YKPmT+fUtrxHa7540CTFnGp8qZrtMEXUUKEwZPoOxdW+sSr3J1vBfOXaTKoMZWoSygnZrXcprs/JEGab73fpnDJX18hQ/DRlHIU4vy8Yb5/9a3lO2dE2AVE75+643QWYd3i8xDZjAdOl3HD7KmOFuDNFZDdi6ygU+/x0x9x2Uf/wYHJDNOvf6r5MwKtxmVQV/zdyXR4RewGAhWW5Y1Qcwg66iCe3BHvpi4+tonKDJK9xpXwlyb3UdOuTZqEddxiYLpXhStrkcuvRUZYdJKHJr0+CaI+3s1ODfA9G0prxOUrnHVC4yudGdJ2Sb/35YYxNCFa8TaMqQW0c3OQPi5hSWnThwY7m4g6lv6zeLCV+bpPyeQI4Aciw6H3sVhx7AnAjkEIPBS6t+a2MC5bUQsjbqYQ5EjtqymhUi7p94yqBTYcttoZbCSvO3ydTVBbgrNZjcU2jBhMksM7rwsQKJgv/c=
